"""Optional real keytool tests: generated disposable PKCS12 files only."""

import os
import shutil
from pathlib import Path

import pytest
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.serialization import pkcs12
from test_unifi_executor import install
from test_unifi_executor import platform as platform

import unifi_executor as executor
from unifi_client import UnifiOperationError
from unifi_executor_files import CANONICAL, ROLLBACK, STAGE
from unifi_process import _run


@pytest.fixture
def java_platform(request, monkeypatch, installation_material):
    p = request.getfixturevalue("platform")
    keytool = os.environ.get("UNIFI_TEST_KEYTOOL") or shutil.which("keytool")
    if not keytool:
        pytest.skip(
            "keytool not installed; set UNIFI_TEST_KEYTOOL for disposable integration"
        )
    # Synthetic private material is generated by the existing fixture. No
    # standalone private-key file is created and no production key is accessed.
    store = pkcs12.serialize_key_and_certificates(
        b"unifi",
        installation_material.key,
        x509.load_der_x509_certificate(p.request.before.certificate_chain_der[0]),
        None,
        serialization.BestAvailableEncryption(b"synthetic-secret"),
    )
    (p.root / CANONICAL).write_bytes(store)

    def run(argv, data, env, lock):
        target = Path(argv[argv.index("-keystore") + 1])
        assert target.resolve().parent == p.root.resolve()
        assert target.name in {CANONICAL, STAGE, ROLLBACK}
        assert "-importcert" not in argv or target.name == STAGE
        return _run((str(keytool), *argv[1:]), data, env, lock)

    monkeypatch.setattr(executor, "_run", run)
    return p


def test_real_keytool_collection_csr_stage_commit_and_recovery(java_platform):
    p = java_platform
    assert p.adapter.inspect_public_state() == p.request.before
    csr = p.adapter.generate_csr(p.request.policy)
    assert x509.load_pem_x509_csr(csr).is_signature_valid
    old_inode = (p.root / CANONICAL).stat().st_ino
    result = install(p)
    assert result.certificate == p.plan.issued
    assert (p.root / ROLLBACK).stat().st_ino == old_inode
    assert (p.root / CANONICAL).stat().st_ino != old_inode
    assert p.adapter.recover() == "service_resumed_pending_live_verification"
    (p.root / CANONICAL).write_bytes(b"disposable corruption")
    assert p.adapter.recover() == "recovered_old"
    assert (p.root / CANONICAL).stat().st_ino == old_inode
    assert p.adapter.inspect_public_state() == p.request.before


def test_real_keytool_failure_cannot_damage_canonical(java_platform, monkeypatch):
    p = java_platform
    original = executor._run

    def bad_reply(argv, data, env, lock):
        if "-importcert" in argv:
            data = b"not a certificate"
        return original(argv, data, env, lock)

    monkeypatch.setattr(executor, "_run", bad_reply)
    with pytest.raises(UnifiOperationError):
        install(p)
    assert p.adapter.recover() == "recovered_old"
    assert p.adapter.inspect_public_state() == p.request.before
